### PR TITLE
Feature/56 change readme logo url

### PR DESCRIPTION
**Pull request by lix-dev**
#56

### CODE REVIEW

**Comment by lix-dev** [comment]
I didnt get a point for this!

"Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate."

**Comment by guyluz11** [comment]
Thanks @lix-dev

**Comment by lix-dev** [comment]
I think you have to write hacktoberfest in lower case!

**Comment by guyluz11** [comment]
@lix-dev  
This project does have "hacktoberfest" topic

image


the label is not the topic, topic is to indicate that I am participating and the label here is to "hacktoberfest-accepted" is that I am approving your request.

Will change the label just in case

**Comment by guyluz11** [comment]
Please update me if that help

**Comment by lix-dev** [comment]
Look at this!

https://ibb.co/nsQBQfP
https://ibb.co/8mxmTxD

**Comment by lix-dev** [comment]
You wrote "hacktob(e)fest" instead of "hacktob(er)fest"!

**Comment by guyluz11** [comment]
Updated
image

Thank you @lix-dev

**Comment by lix-dev** [comment]
Now i get it, thank you ;)

**Comment by guyluz11** [comment]
If you would like to help us make the world a better place a star to the project will help.

Happy hacktob(er)fest :)

**Pull request merged**
