### PR TITLE
Updated readme with new snap link

### LINKED ISSUE #144: Move to different snap name
The snap of cbj_smart_device use the snap name cybear-jinni, it need  to move to cbj-smart-device.
cybear-jinni will be used by the app, on all platform the app should have only the company name.

image

### PR DESCRIPTION
**Pull request by acenasir**
https://snapcraft.io/cbj-smart-device

### CODE REVIEW

**Comment by acenasir** [comment]
#hacketoberfest

**Comment by guyluz11** [comment]
Hi @acenasir 

Can you change your pr to dev branch?


Thanks

**Comment by acenasir** [comment]
Done @guyluz11

**Comment by guyluz11** [comment]
Thanks for the pr @acenasir and a happy Hacktoberfest 😁

**Pull request merged**
