### PR TITLE
Add badge for Snapcraft

### LINKED ISSUE #81: Add snap badge to readme file
Add snap badge to readme file example can be found here

https://github.com/tqdm/tqdm

image

Make it link to [our page](https://snapcraft.io/cybear-jinni) in the snapcraft store 

I prefer the new logo with the orange nose if you can fined as a badge or create it. 

image

### PR DESCRIPTION
**Pull request by sofiacarballo**
Closes #81

### CODE REVIEW

**Comment by guyluz11** [comment]
Thanks @sofiacarballo 

Thanks for updating the image, is there a way to make the URL of it smaller ?

**Comment by guyluz11** [comment]
And just if you want you can change the install background to be the same green as the bird

**Comment by sofiacarballo** [comment]
@guyluz11 I think that it cannot be shortened since is a base64 string .If I reduce it, some of the data may be lost. What I can do is use the default icon image from Shields, the one without the orange beak.
The color is the same one, #82BEA0

**Comment by guyluz11** [comment]
Try this one https://rb.gy/0gntiy

**Comment by guyluz11** [comment]
Thanks for the pull request @sofiacarballo

**Comment by guyluz11** [comment]
If you would like to help us make the world a better place a ⭐star🌟 to the project will help.

Happy hacktoberfest :)

**Pull request merged**
