### PR TITLE
Fixes issue #66

### PR DESCRIPTION
**Pull request by Tazminia**

### CODE REVIEW

**Comment by Tazminia** [comment]
This PR is now targeting dev branch as requested

**Comment by Tazminia** [comment]
@guyluz11 any idea why is this PR not counting in my hacktoberfest profile ?

**Comment by guyluz11** [comment]
Hello @Tazminia and thanks for the pull request.

In order for the pull request to be get review and get counting I need to add label which I will do now

**Comment by guyluz11** [comment]
If you would like to help us make the world a better place a ⭐star🌟 to the project will help.

Happy hacktoberfest :)

**Pull request merged**
